### ISSUE TITLE
Decide Server side tech stack and communication protocol

### ISSUE THREAD

**Issue by kkimdev** [m19g/online-test#4]
Let me know if you have any thoughts

Candidates in my mind:
- Java
- Python
- NodeJS
- Rust

**Comment by abhisheks043** [comment]
Java and NodeJS will be preferred

**Comment by kkimdev** [comment]
OK seems like these are the popular frameworks:
- Play 2
- Spring Boot
- Express JS
- Koa

**Comment by kkimdev** [comment]
FYI: http://www.ybrikman.com/writing/2014/09/29/nodejs-vs-play-framework/ (I haven't read yet)

**Comment by kkimdev** [comment]
OK let's try NodeJS + Express Js as it seems the most popular choice with Angular2, https://expressjs.com/

**Comment by abhisheks043** [comment]
Yea, MEAN stack development could be useful.
