### ISSUE TITLE
Distinguish Session finished / session does not exist

### ISSUE THREAD

**Issue by kkimdev** [m19g/online-test#50]
We should distinguish session finished / session does not exist by keeping the finished sessions.

**Comment by erashu212** [comment]
@kkimdev : Can you explain more about this?

**Comment by kkimdev** [comment]
For example, if user opens http://localhost:4200/test/1493023944455 but there is no session id 1493023944455 , then we shouldn't say the test is finished.  Either 404 error or "invalid session" message would be correct.

**Comment by erashu212** [comment]
@kkimdev : Okay
