### ISSUE TITLE
Maintain session on refreshing.

### ISSUE THREAD

**Issue by kkimdev** [m19g/online-test#51]
Currently refreshing just restarts the whole session.  Note:  We should not rely on timeout.  Instead, server should keep updating the state.

For example, if problem time limit is 20 min, and a test taker opened the test url, and closed, and opened 15 min later, then it should show 5 min left.

**Comment by erashu212** [comment]
@kkimdev : I think for this problem DB needs to come into picture. Let me know what do you think?

**Comment by erashu212** [comment]
#47
